### ISSUE TITLE
Release v1.0

### ISSUE THREAD

**Issue by navidcy** [Josue-Martinez-Moreno/trackeddy#4]
I suggest doing a release of v1.0 (which is the version used in the [paper](https://doi.org/10.1029/2019MS001769).

<img width="1008" alt="Screen Shot 2019-10-30 at 12 13 37 PM" src="https://user-images.githubusercontent.com/7112768/67820808-d600c780-fb0e-11e9-8a7c-008eaf0c93ab.png">

**Comment by josuemtzmo** [comment]
Thanks for the suggestion, I've done it. 
J
